name: Ruby

on: [push,pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        ruby-version: ['3.0', '3.1', '3.2', head]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
    - name: Install gem dependencies
      run: |
        gem install bundler
        bundle install
        cd sorbet/example_consumer
        bundle install
        cd ../..
    - name: Run the test script
      run: ./script/test
