name: Ruby

on: [push,pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        ruby-version: ['3.0', '3.1']

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
    - name: Run the default task
      run: |
        gem install bundler
        bundle install
        bundle exec rake
